[2020-12-15 15:00:23,624] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-15T09:25:00+00:00 [queued]>
[2020-12-15 15:00:23,637] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-15T09:25:00+00:00 [queued]>
[2020-12-15 15:00:23,638] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-15 15:00:23,638] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-15 15:00:23,638] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-15 15:00:23,643] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table2> on 2020-12-15T09:25:00+00:00
[2020-12-15 15:00:23,645] {standard_task_runner.py:54} INFO - Started process 66287 to run task
[2020-12-15 15:00:23,676] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table2', '2020-12-15T09:25:00+00:00', '--job_id', '1628', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmp_kaqyg37']
[2020-12-15 15:00:23,678] {standard_task_runner.py:78} INFO - Job 1628: Subtask Data_from_table2
[2020-12-15 15:00:23,712] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table2 2020-12-15T09:25:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-12-15 15:00:23,743] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-15 15:00:23,743] {logging_mixin.py:112} INFO - 
[2020-12-15 15:00:23,743] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-15 15:00:23,747] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table2, execution_date=20201215T092500, start_date=20201215T093023, end_date=20201215T093023
[2020-12-15 15:00:28,621] {local_task_job.py:102} INFO - Task exited with return code 0
