[2020-12-14 15:30:35,159] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: First_DAG_for_test.print_data 2020-12-14T09:00:00+00:00 [queued]>
[2020-12-14 15:30:35,168] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: First_DAG_for_test.print_data 2020-12-14T09:00:00+00:00 [queued]>
[2020-12-14 15:30:35,168] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-14 15:30:35,168] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-14 15:30:35,168] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-14 15:30:35,174] {taskinstance.py:901} INFO - Executing <Task(BashOperator): print_data> on 2020-12-14T09:00:00+00:00
[2020-12-14 15:30:35,176] {standard_task_runner.py:54} INFO - Started process 22954 to run task
[2020-12-14 15:30:35,202] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'First_DAG_for_test', 'print_data', '2020-12-14T09:00:00+00:00', '--job_id', '1115', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/sampleDag.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpiy0mawrn']
[2020-12-14 15:30:35,203] {standard_task_runner.py:78} INFO - Job 1115: Subtask print_data
[2020-12-14 15:30:35,233] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: First_DAG_for_test.print_data 2020-12-14T09:00:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-12-14 15:30:35,252] {bash_operator.py:113} INFO - Tmp dir root location: 
 /var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T
[2020-12-14 15:30:35,253] {bash_operator.py:134} INFO - Temporary script location: /var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/airflowtmp57nrstjn/print_data0zfjv0ci
[2020-12-14 15:30:35,254] {bash_operator.py:146} INFO - Running command: python3 /Users/sundarb/Desktop/print.py
[2020-12-14 15:30:35,260] {bash_operator.py:153} INFO - Output:
[2020-12-14 15:30:35,305] {bash_operator.py:157} INFO - /Users/sundarb/airflow/venv/bin/python3: can't open file '/Users/sundarb/Desktop/print.py': [Errno 2] No such file or directory
[2020-12-14 15:30:35,309] {bash_operator.py:159} INFO - Command exited with return code 2
[2020-12-14 15:30:35,316] {taskinstance.py:1150} ERROR - Bash command failed
Traceback (most recent call last):
  File "/Users/sundarb/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/sundarb/airflow/venv/lib/python3.8/site-packages/airflow/operators/bash_operator.py", line 165, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-12-14 15:30:35,320] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=First_DAG_for_test, task_id=print_data, execution_date=20201214T090000, start_date=20201214T100035, end_date=20201214T100035
[2020-12-14 15:30:40,160] {local_task_job.py:102} INFO - Task exited with return code 1
