[2020-11-29 20:22:36,060] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: First_DAG_for_test.read_csv 2020-11-29T13:00:00+00:00 [queued]>
[2020-11-29 20:22:36,077] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: First_DAG_for_test.read_csv 2020-11-29T13:00:00+00:00 [queued]>
[2020-11-29 20:22:36,077] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-11-29 20:22:36,077] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-11-29 20:22:36,077] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-11-29 20:22:36,089] {taskinstance.py:901} INFO - Executing <Task(BashOperator): read_csv> on 2020-11-29T13:00:00+00:00
[2020-11-29 20:22:36,092] {standard_task_runner.py:54} INFO - Started process 10105 to run task
[2020-11-29 20:22:36,108] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'First_DAG_for_test', 'read_csv', '2020-11-29T13:00:00+00:00', '--job_id', '272', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/sampleDag.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpipod4a4i']
[2020-11-29 20:22:36,109] {standard_task_runner.py:78} INFO - Job 272: Subtask read_csv
[2020-11-29 20:22:36,152] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: First_DAG_for_test.read_csv 2020-11-29T13:00:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-11-29 20:22:36,179] {bash_operator.py:113} INFO - Tmp dir root location: 
 /var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T
[2020-11-29 20:22:36,181] {bash_operator.py:136} INFO - Temporary script location: /var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/airflowtmp6eqtukdw/read_csv7d3ck0sk
[2020-11-29 20:22:36,181] {bash_operator.py:146} INFO - Running command: python3 /Users/sundarb/Documents/DEWorkspace/postgresSample.conf
[2020-11-29 20:22:36,187] {bash_operator.py:153} INFO - Output:
[2020-11-29 20:22:36,278] {bash_operator.py:157} INFO - python3: can't open file '/Users/sundarb/Documents/DEWorkspace/postgresSample.conf': [Errno 2] No such file or directory
[2020-11-29 20:22:36,282] {bash_operator.py:161} INFO - Command exited with return code 2
[2020-11-29 20:22:36,287] {taskinstance.py:1150} ERROR - Bash command failed
Traceback (most recent call last):
  File "/Users/sundarb/Documents/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/sundarb/Documents/anaconda3/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 165, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-11-29 20:22:36,290] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=First_DAG_for_test, task_id=read_csv, execution_date=20201129T130000, start_date=20201129T145236, end_date=20201129T145236
[2020-11-29 20:22:41,087] {local_task_job.py:102} INFO - Task exited with return code 1
