[2020-12-11 12:20:05,156] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-11T06:40:00+00:00 [queued]>
[2020-12-11 12:20:05,164] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-11T06:40:00+00:00 [queued]>
[2020-12-11 12:20:05,164] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 12:20:05,164] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-11 12:20:05,164] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 12:20:05,169] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table1> on 2020-12-11T06:40:00+00:00
[2020-12-11 12:20:05,171] {standard_task_runner.py:54} INFO - Started process 90712 to run task
[2020-12-11 12:20:05,197] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table1', '2020-12-11T06:40:00+00:00', '--job_id', '781', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmplxpttlru']
[2020-12-11 12:20:05,198] {standard_task_runner.py:78} INFO - Job 781: Subtask Data_from_table1
[2020-12-11 12:20:05,227] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table1 2020-12-11T06:40:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-12-11 12:20:05,267] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-11 12:20:05,268] {logging_mixin.py:112} INFO - 
[2020-12-11 12:20:05,268] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-11 12:20:05,273] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table1, execution_date=20201211T064000, start_date=20201211T065005, end_date=20201211T065005
[2020-12-11 12:20:10,170] {local_task_job.py:102} INFO - Task exited with return code 0
