[2020-12-16 11:05:02,377] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-16T05:30:00+00:00 [queued]>
[2020-12-16 11:05:02,386] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-16T05:30:00+00:00 [queued]>
[2020-12-16 11:05:02,387] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-16 11:05:02,387] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-16 11:05:02,387] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-16 11:05:02,392] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table1> on 2020-12-16T05:30:00+00:00
[2020-12-16 11:05:02,395] {standard_task_runner.py:54} INFO - Started process 76941 to run task
[2020-12-16 11:05:02,424] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table1', '2020-12-16T05:30:00+00:00', '--job_id', '1713', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpwngig0q7']
[2020-12-16 11:05:02,426] {standard_task_runner.py:78} INFO - Job 1713: Subtask Data_from_table1
[2020-12-16 11:05:02,453] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table1 2020-12-16T05:30:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-12-16 11:05:02,484] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-16 11:05:02,485] {logging_mixin.py:112} INFO - 
[2020-12-16 11:05:02,485] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-16 11:05:02,488] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table1, execution_date=20201216T053000, start_date=20201216T053502, end_date=20201216T053502
[2020-12-16 11:05:07,371] {local_task_job.py:102} INFO - Task exited with return code 0
