[2020-12-15 03:15:05,461] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-14T20:40:00+00:00 [queued]>
[2020-12-15 03:15:05,469] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-14T20:40:00+00:00 [queued]>
[2020-12-15 03:15:05,470] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-15 03:15:05,470] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-15 03:15:05,470] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-15 03:15:05,475] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table2> on 2020-12-14T20:40:00+00:00
[2020-12-15 03:15:05,477] {standard_task_runner.py:54} INFO - Started process 43076 to run task
[2020-12-15 03:15:05,505] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table2', '2020-12-14T20:40:00+00:00', '--job_id', '1295', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpg29g5dzf']
[2020-12-15 03:15:05,507] {standard_task_runner.py:78} INFO - Job 1295: Subtask Data_from_table2
[2020-12-15 03:15:05,534] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table2 2020-12-14T20:40:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-12-15 03:15:05,556] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-15 03:15:05,557] {logging_mixin.py:112} INFO - 
[2020-12-15 03:15:05,557] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-15 03:15:05,560] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table2, execution_date=20201214T204000, start_date=20201214T214505, end_date=20201214T214505
[2020-12-15 03:15:10,725] {local_task_job.py:102} INFO - Task exited with return code 0
