[2020-12-09 13:26:15,234] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-09T07:50:00+00:00 [queued]>
[2020-12-09 13:26:15,245] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-09T07:50:00+00:00 [queued]>
[2020-12-09 13:26:15,245] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-09 13:26:15,245] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-09 13:26:15,245] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-09 13:26:15,252] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table2> on 2020-12-09T07:50:00+00:00
[2020-12-09 13:26:15,254] {standard_task_runner.py:54} INFO - Started process 48147 to run task
[2020-12-09 13:26:15,289] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table2', '2020-12-09T07:50:00+00:00', '--job_id', '510', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpa8c0zlyx']
[2020-12-09 13:26:15,290] {standard_task_runner.py:78} INFO - Job 510: Subtask Data_from_table2
[2020-12-09 13:26:15,326] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table2 2020-12-09T07:50:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-12-09 13:26:15,348] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-09 13:26:15,349] {logging_mixin.py:112} INFO - 
[2020-12-09 13:26:15,349] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-09 13:26:15,353] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table2, execution_date=20201209T075000, start_date=20201209T075615, end_date=20201209T075615
[2020-12-09 13:26:20,233] {local_task_job.py:102} INFO - Task exited with return code 0
