[2020-12-16 09:16:04,792] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-16T03:40:00+00:00 [queued]>
[2020-12-16 09:16:04,909] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-16T03:40:00+00:00 [queued]>
[2020-12-16 09:16:04,911] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-16 09:16:04,912] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-16 09:16:04,913] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-16 09:16:04,985] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table1> on 2020-12-16T03:40:00+00:00
[2020-12-16 09:16:05,005] {standard_task_runner.py:54} INFO - Started process 70371 to run task
[2020-12-16 09:16:05,405] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table1', '2020-12-16T03:40:00+00:00', '--job_id', '1675', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpkf6qw9k1']
[2020-12-16 09:16:05,438] {standard_task_runner.py:78} INFO - Job 1675: Subtask Data_from_table1
[2020-12-16 09:16:05,950] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table1 2020-12-16T03:40:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-12-16 09:16:06,230] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-16 09:16:06,234] {logging_mixin.py:112} INFO - 
[2020-12-16 09:16:06,237] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-16 09:16:06,283] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table1, execution_date=20201216T034000, start_date=20201216T034604, end_date=20201216T034606
[2020-12-16 09:16:09,630] {local_task_job.py:102} INFO - Task exited with return code 0
