[2020-12-09 10:20:02,954] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-09T03:10:00+00:00 [queued]>
[2020-12-09 10:20:02,960] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-09T03:10:00+00:00 [queued]>
[2020-12-09 10:20:02,960] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-09 10:20:02,960] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-09 10:20:02,960] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-09 10:20:02,965] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table1> on 2020-12-09T03:10:00+00:00
[2020-12-09 10:20:02,967] {standard_task_runner.py:54} INFO - Started process 36521 to run task
[2020-12-09 10:20:02,994] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table1', '2020-12-09T03:10:00+00:00', '--job_id', '405', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpd0cmmarh']
[2020-12-09 10:20:02,995] {standard_task_runner.py:78} INFO - Job 405: Subtask Data_from_table1
[2020-12-09 10:20:03,021] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table1 2020-12-09T03:10:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-12-09 10:20:03,038] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-09 10:20:03,039] {logging_mixin.py:112} INFO - 
[2020-12-09 10:20:03,039] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-09 10:20:03,042] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table1, execution_date=20201209T031000, start_date=20201209T045002, end_date=20201209T045003
[2020-12-09 10:20:07,954] {local_task_job.py:102} INFO - Task exited with return code 0
