[2020-12-14 20:05:16,153] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-14T14:30:00+00:00 [queued]>
[2020-12-14 20:05:16,163] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-14T14:30:00+00:00 [queued]>
[2020-12-14 20:05:16,163] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-14 20:05:16,163] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-14 20:05:16,164] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-14 20:05:16,171] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table1> on 2020-12-14T14:30:00+00:00
[2020-12-14 20:05:16,175] {standard_task_runner.py:54} INFO - Started process 34307 to run task
[2020-12-14 20:05:16,216] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table1', '2020-12-14T14:30:00+00:00', '--job_id', '1214', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmp9pkjsyk1']
[2020-12-14 20:05:16,218] {standard_task_runner.py:78} INFO - Job 1214: Subtask Data_from_table1
[2020-12-14 20:05:16,254] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table1 2020-12-14T14:30:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-12-14 20:05:16,288] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-14 20:05:16,288] {logging_mixin.py:112} INFO - 
[2020-12-14 20:05:16,289] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-14 20:05:16,293] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table1, execution_date=20201214T143000, start_date=20201214T143516, end_date=20201214T143516
[2020-12-14 20:05:21,153] {local_task_job.py:102} INFO - Task exited with return code 0
