[2020-12-10 13:25:22,376] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-10T07:50:00+00:00 [queued]>
[2020-12-10 13:25:22,393] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-10T07:50:00+00:00 [queued]>
[2020-12-10 13:25:22,393] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-10 13:25:22,394] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-10 13:25:22,394] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-10 13:25:22,403] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table2> on 2020-12-10T07:50:00+00:00
[2020-12-10 13:25:22,407] {standard_task_runner.py:54} INFO - Started process 72005 to run task
[2020-12-10 13:25:22,455] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table2', '2020-12-10T07:50:00+00:00', '--job_id', '612', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpfd2xgj96']
[2020-12-10 13:25:22,458] {standard_task_runner.py:78} INFO - Job 612: Subtask Data_from_table2
[2020-12-10 13:25:22,507] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table2 2020-12-10T07:50:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-12-10 13:25:22,541] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-10 13:25:22,541] {logging_mixin.py:112} INFO - 
[2020-12-10 13:25:22,541] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-10 13:25:22,547] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table2, execution_date=20201210T075000, start_date=20201210T075522, end_date=20201210T075522
[2020-12-10 13:25:27,361] {local_task_job.py:102} INFO - Task exited with return code 0
