[2020-12-16 20:06:56,875] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-16T14:30:00+00:00 [queued]>
[2020-12-16 20:06:56,917] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-16T14:30:00+00:00 [queued]>
[2020-12-16 20:06:56,917] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-16 20:06:56,918] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-16 20:06:56,918] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-16 20:06:56,931] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table2> on 2020-12-16T14:30:00+00:00
[2020-12-16 20:06:56,936] {standard_task_runner.py:54} INFO - Started process 4408 to run task
[2020-12-16 20:06:57,045] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table2', '2020-12-16T14:30:00+00:00', '--job_id', '1885', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpcx0h97o6']
[2020-12-16 20:06:57,048] {standard_task_runner.py:78} INFO - Job 1885: Subtask Data_from_table2
[2020-12-16 20:06:57,137] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table2 2020-12-16T14:30:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-12-16 20:06:57,243] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-16 20:06:57,245] {logging_mixin.py:112} INFO - 
[2020-12-16 20:06:57,246] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-16 20:06:57,256] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table2, execution_date=20201216T143000, start_date=20201216T143656, end_date=20201216T143657
[2020-12-16 20:07:01,987] {local_task_job.py:102} INFO - Task exited with return code 0
