[2020-12-30 11:30:25,486] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-30T05:55:00+00:00 [queued]>
[2020-12-30 11:30:25,496] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-30T05:55:00+00:00 [queued]>
[2020-12-30 11:30:25,497] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-30 11:30:25,497] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-30 11:30:25,497] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-30 11:30:25,502] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table2> on 2020-12-30T05:55:00+00:00
[2020-12-30 11:30:25,505] {standard_task_runner.py:54} INFO - Started process 61746 to run task
[2020-12-30 11:30:25,534] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table2', '2020-12-30T05:55:00+00:00', '--job_id', '1945', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmp81g8ssji']
[2020-12-30 11:30:25,536] {standard_task_runner.py:78} INFO - Job 1945: Subtask Data_from_table2
[2020-12-30 11:30:25,563] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table2 2020-12-30T05:55:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-12-30 11:30:25,588] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-30 11:30:25,589] {logging_mixin.py:112} INFO - 
[2020-12-30 11:30:25,589] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-30 11:30:25,593] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table2, execution_date=20201230T055500, start_date=20201230T060025, end_date=20201230T060025
[2020-12-30 11:30:30,481] {local_task_job.py:102} INFO - Task exited with return code 0
