[2020-12-09 13:35:20,862] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-09T08:00:00+00:00 [queued]>
[2020-12-09 13:35:20,874] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-09T08:00:00+00:00 [queued]>
[2020-12-09 13:35:20,874] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-09 13:35:20,874] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-09 13:35:20,874] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-09 13:35:20,880] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table2> on 2020-12-09T08:00:00+00:00
[2020-12-09 13:35:20,883] {standard_task_runner.py:54} INFO - Started process 48980 to run task
[2020-12-09 13:35:20,914] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table2', '2020-12-09T08:00:00+00:00', '--job_id', '516', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmp6zhl9afc']
[2020-12-09 13:35:20,915] {standard_task_runner.py:78} INFO - Job 516: Subtask Data_from_table2
[2020-12-09 13:35:20,948] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table2 2020-12-09T08:00:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-12-09 13:35:20,973] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-09 13:35:20,973] {logging_mixin.py:112} INFO - 
[2020-12-09 13:35:20,973] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-09 13:35:20,977] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table2, execution_date=20201209T080000, start_date=20201209T080520, end_date=20201209T080520
[2020-12-09 13:35:25,859] {local_task_job.py:102} INFO - Task exited with return code 0
