[2020-12-16 17:15:07,505] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-16T11:40:00+00:00 [queued]>
[2020-12-16 17:15:07,517] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-16T11:40:00+00:00 [queued]>
[2020-12-16 17:15:07,517] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-16 17:15:07,517] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-16 17:15:07,518] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-16 17:15:07,524] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table2> on 2020-12-16T11:40:00+00:00
[2020-12-16 17:15:07,526] {standard_task_runner.py:54} INFO - Started process 97204 to run task
[2020-12-16 17:15:07,560] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table2', '2020-12-16T11:40:00+00:00', '--job_id', '1843', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpcfqnhy6r']
[2020-12-16 17:15:07,561] {standard_task_runner.py:78} INFO - Job 1843: Subtask Data_from_table2
[2020-12-16 17:15:07,591] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table2 2020-12-16T11:40:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-12-16 17:15:07,613] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-16 17:15:07,613] {logging_mixin.py:112} INFO - 
[2020-12-16 17:15:07,613] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-16 17:15:07,616] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table2, execution_date=20201216T114000, start_date=20201216T114507, end_date=20201216T114507
[2020-12-16 17:15:12,499] {local_task_job.py:102} INFO - Task exited with return code 0
