[2020-12-15 05:45:37,836] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-15T00:10:00+00:00 [queued]>
[2020-12-15 05:45:37,845] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-15T00:10:00+00:00 [queued]>
[2020-12-15 05:45:37,845] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-15 05:45:37,845] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-15 05:45:37,845] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-15 05:45:37,851] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table1> on 2020-12-15T00:10:00+00:00
[2020-12-15 05:45:37,853] {standard_task_runner.py:54} INFO - Started process 44072 to run task
[2020-12-15 05:45:37,885] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table1', '2020-12-15T00:10:00+00:00', '--job_id', '1334', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpf7hubdch']
[2020-12-15 05:45:37,887] {standard_task_runner.py:78} INFO - Job 1334: Subtask Data_from_table1
[2020-12-15 05:45:37,918] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table1 2020-12-15T00:10:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-12-15 05:45:37,939] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-15 05:45:37,940] {logging_mixin.py:112} INFO - 
[2020-12-15 05:45:37,940] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-15 05:45:37,943] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table1, execution_date=20201215T001000, start_date=20201215T001537, end_date=20201215T001537
[2020-12-15 05:45:42,833] {local_task_job.py:102} INFO - Task exited with return code 0
