[2020-12-13 14:03:06,845] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-13T08:25:00+00:00 [queued]>
[2020-12-13 14:03:06,863] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-13T08:25:00+00:00 [queued]>
[2020-12-13 14:03:06,863] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-13 14:03:06,863] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-13 14:03:06,863] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-13 14:03:06,871] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table1> on 2020-12-13T08:25:00+00:00
[2020-12-13 14:03:06,875] {standard_task_runner.py:54} INFO - Started process 200 to run task
[2020-12-13 14:03:06,925] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table1', '2020-12-13T08:25:00+00:00', '--job_id', '879', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmp1gpqiyae']
[2020-12-13 14:03:06,928] {standard_task_runner.py:78} INFO - Job 879: Subtask Data_from_table1
[2020-12-13 14:03:06,975] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table1 2020-12-13T08:25:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-12-13 14:03:07,009] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-13 14:03:07,009] {logging_mixin.py:112} INFO - 
[2020-12-13 14:03:07,010] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-13 14:03:07,015] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table1, execution_date=20201213T082500, start_date=20201213T083306, end_date=20201213T083307
[2020-12-13 14:03:11,949] {local_task_job.py:102} INFO - Task exited with return code 0
