[2020-12-15 13:35:18,315] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-15T08:00:00+00:00 [queued]>
[2020-12-15 13:35:18,327] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-15T08:00:00+00:00 [queued]>
[2020-12-15 13:35:18,327] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-15 13:35:18,328] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-15 13:35:18,328] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-15 13:35:18,334] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table1> on 2020-12-15T08:00:00+00:00
[2020-12-15 13:35:18,337] {standard_task_runner.py:54} INFO - Started process 62191 to run task
[2020-12-15 13:35:18,368] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table1', '2020-12-15T08:00:00+00:00', '--job_id', '1590', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmprstk6f2a']
[2020-12-15 13:35:18,370] {standard_task_runner.py:78} INFO - Job 1590: Subtask Data_from_table1
[2020-12-15 13:35:18,399] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table1 2020-12-15T08:00:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-12-15 13:35:18,449] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-15 13:35:18,450] {logging_mixin.py:112} INFO - 
[2020-12-15 13:35:18,450] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-15 13:35:18,455] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table1, execution_date=20201215T080000, start_date=20201215T080518, end_date=20201215T080518
[2020-12-15 13:35:23,309] {local_task_job.py:102} INFO - Task exited with return code 0
