[2020-11-29 09:34:24,754] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: First_DAG_for_test.read_csv 2020-11-29T03:00:00+00:00 [queued]>
[2020-11-29 09:34:24,766] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: First_DAG_for_test.read_csv 2020-11-29T03:00:00+00:00 [queued]>
[2020-11-29 09:34:24,766] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-11-29 09:34:24,766] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-11-29 09:34:24,766] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-11-29 09:34:24,811] {taskinstance.py:901} INFO - Executing <Task(BashOperator): read_csv> on 2020-11-29T03:00:00+00:00
[2020-11-29 09:34:24,813] {standard_task_runner.py:54} INFO - Started process 9632 to run task
[2020-11-29 09:34:24,829] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'First_DAG_for_test', 'read_csv', '2020-11-29T03:00:00+00:00', '--job_id', '270', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/sampleDag.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpf3wslj12']
[2020-11-29 09:34:24,831] {standard_task_runner.py:78} INFO - Job 270: Subtask read_csv
[2020-11-29 09:34:24,858] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: First_DAG_for_test.read_csv 2020-11-29T03:00:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-11-29 09:34:24,877] {bash_operator.py:113} INFO - Tmp dir root location: 
 /var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T
[2020-11-29 09:34:24,879] {bash_operator.py:136} INFO - Temporary script location: /var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/airflowtmpahvi23uo/read_csvquk5glsn
[2020-11-29 09:34:24,879] {bash_operator.py:146} INFO - Running command: python3 /Users/sundarb/Documents/DEWorkspace/postgresSample.conf
[2020-11-29 09:34:24,886] {bash_operator.py:153} INFO - Output:
[2020-11-29 09:34:24,971] {bash_operator.py:157} INFO - python3: can't open file '/Users/sundarb/Documents/DEWorkspace/postgresSample.conf': [Errno 2] No such file or directory
[2020-11-29 09:34:24,974] {bash_operator.py:161} INFO - Command exited with return code 2
[2020-11-29 09:34:24,980] {taskinstance.py:1150} ERROR - Bash command failed
Traceback (most recent call last):
  File "/Users/sundarb/Documents/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/sundarb/Documents/anaconda3/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 165, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-11-29 09:34:24,984] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=First_DAG_for_test, task_id=read_csv, execution_date=20201129T030000, start_date=20201129T040424, end_date=20201129T040424
[2020-11-29 09:34:31,029] {local_task_job.py:102} INFO - Task exited with return code 1
